#!/bin/bash

# check
if [ ! -d /backups ]; then
        echo "$0: Directory /backups does not exist!"
        exit 1
fi

if [ $(ls -1A /backups/*7z | wc -l) -eq 0 ]; then
        echo "$0: Backup directory is empty!"
        exit 2
fi

# load environment variables pertaining to wordpress (starting with "WORDPRESS_")
source <(sed -r -n 's/[^#]+/export &/ p' /setup/*.env)

# debug set to false by default; can be set to true with option -d
# if debug is true, the backup file is only extracted into a temporary directory, see below
DEBUG=false

# by default, the newest file in the backup directory is chosen
BACKUPFILE=$(ls /backups/*.7z -t | head -n1)

# get options for debug and use a specific backup file
while getopts "df:" OPTION; do
        case $OPTION in
                d)
                        DEBUG=true
                        ;;
                f)
                        BACKUPFILE=$OPTARG
                        if [ ! -f $BACKUPFILE ]; then
                                echo "The supplied file $BACKUPFILE does not exist!"
                                exit 3
                        fi
                        ;;
                \?)
                        echo "Only options -d (= debug flag) and -f (= backup file) are implemented."
                        exit 4
                        ;;
        esac
done

# Timestamp etc.
TSTMP=$(date +"%Y%m%d_%H%M")
EXTRACTDIR=/tmp/${TSTMP}
UNTARDIR=${EXTRACTDIR}/untar

# extract to temporary directory and untar contents
7zr -o${EXTRACTDIR} e ${BACKUPFILE}
mkdir ${UNTARDIR}
tar -xf ${EXTRACTDIR}/*.tar -C ${UNTARDIR}

# pass files to restore scripts and clean up
if [ "$DEBUG" == false ]; then
	# restore db
        wordpress-restore-db-from-dump ${EXTRACTDIR}/*.sql ${EXTRACTDIR}/*.env

	# remove and recreate install directory
	if [ -d ${WORDPRESS_INSTALL_PATH} ]; then
		rm -R ${WORDPRESS_INSTALL_PATH}
		echo "$0: install directory ${WORDPRESS_INSTALL_PATH} removed"
		mkdir -p ${WORDPRESS_INSTALL_PATH}
		echo "$0: install directory ${WORDPRESS_INSTALL_PATH} recreated"
	else
		mkdir -p ${WORDPRESS_INSTALL_PATH}
		echo "$0: install directory ${WORDPRESS_INSTALL_PATH} created"
	fi

	# copy contents of $UNTARDIR into $WORDPRESS_INSTALL_PATH
	cp -a ${UNTARDIR}/. ${WORDPRESS_INSTALL_PATH}

	# configure wordpress
	wordpress-configure-wp

	# clean up
        rm -R ${EXTRACTDIR}
fi

# echo success
if [ $? -eq 0 ]; then
	echo "$0: wordpress backup has successfully been restored from $BACKUPFILE."
else
	echo "$0: there was a problem restoring wordpress backup $BACKUPFILE!"
	exit 3
fi

exit 0

