#!/bin/bash

# check
if [ $# -lt 1 ]; then
	echo 1>&2 "$0: Please provide the sql dump file."
	exit 1
fi

# extract sql dump and env files from arguments
SQLDUMP=$1
#ENVFILE=$2

# load environment variables pertaining to wordpress (starting with "WORDPRESS_")
source <(sed -r -n 's/[^#]+/export &/ p' /setup/*.env)

# timestamp
TSTMP=$(date +"%Y%m%d_%H%M")

# mysql exec common trunc
MEXEC="mysql -h ${WORDPRESS_DB_SERVER} -P ${WORDPRESS_DB_PORT} -u${WORDPRESS_DB_USER} -p${WORDPRESS_DB_PASSWORD} ${WORDPRESS_DB_NAME}"
 
# retrieve table names
TABLES=$(${MEXEC} -e 'show tables' | cut -f1 | grep -v '^Tables' )

if [ ${#TABLES} -gt 0 ]; then
	echo "$0: Found ${#TABLES} tables in database ${WORDPRESS_DB_NAME}."
	# delete tables one by one
	for t in $TABLES
	do
		echo "$0: Deleting table $t from database $WORDPRESS_DB_NAME ..."
		${MEXEC} -e "drop table $t"
	done
else
	echo "$0: Database ${WORDPRESS_DB_NAME} did not contain any tables. No change necessary."
fi

# Problem?
if [ $? -ne 0 ]; then
	echo "$0: there was a problem deleting the old tables!"
	exit 3
fi

# restore from dump
echo "$0: restoring database $WORDPRESS_DB_NAME from $SQLDUMP ..."
${MEXEC} < ${SQLDUMP}

# Problem?
if [ $? -ne 0 ]; then
	echo "$0: there was a problem with restoring database $WORDPRESS_DB_NAME from $SQLDUMP!"
	exit 4
fi

# adjust home and siteurl
wp --allow-root --path=${WORDPRESS_INSTALL_PATH} option update home ${WORDPRESS_SITE_URL} && wp --allow-root --path=${WORDPRESS_INSTALL_PATH} option update siteurl ${WORDPRESS_SITE_URL} 
# Problem?
if [ $? -ne 0 ]; then
	echo "$0: there was a problem with changing 'home' or 'siteurl'!"
	exit 5
fi

# echo success
echo "$0: database ${WORDPRESS_DB_NAME} has successfully been restored from ${SQLDUMP}."

exit 0
